version: '3'

services:
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
                TIMEZONE: Europe/Madrid
        volumes:
            - ./:/var/www/librarify/
        networks:
            - symfony
    nginx:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/librarify/
        ports:
            - 82:80
        networks:
            - symfony
    db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db_library:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: chopin
            MYSQL_DATABASE: library
            MYSQL_USER: nil
            MYSQL_PASSWORD: chopin
        ports:
            - 3308:3306
        networks:
            - symfony

volumes:
    librarifyback_app_sync:
        external: true
    db_library:

networks:
    symfony:
