library_list:
    path: /library/list
    controller: App\Controller\LibraryController::list
    methods:  [GET]
library_createbook:
    path: /library/createbook
    controller: App\Controller\LibraryController::createBook
    methods:  [GET] 

#Books
book_controller_get:
    path: /api/books
    controller: App\Controller\Api\BooksController::get
    methods:  [GET] 
book_controller_get_id:
    path: /api/books/{id}
    controller: App\Controller\Api\BooksController::getById
    methods:  [GET]
#    format: json
#    requirements:
#        _format: json
book_controller_post:
    path: /api/books
    controller: App\Controller\Api\BooksController::post
    methods:  [POST] 
book_controller_edit:
    path: /api/put/{id}
    controller: App\Controller\Api\BooksController::put
    methods : [PUT]
book_controller_delete:
    path: /api/books/{id}
    controller: App\Controller\Api\BooksController::delete
    methods : [DELETE]
book_controller_patch:
    path: /api/patch_book/{id}
    controller: App\Controller\Api\BooksController::patch
    methods : [PATCH]

#Authors
author_controller_get:
    path: /api/author
    controller: App\Controller\Api\AuthorController::index
    methods:  [GET] 

author_controller_post:
    path: /api/author
    controller: App\Controller\Api\AuthorController::post
    methods:  [POST] 

#Isbn
isbn_controller_get:
    path: /api/isbn
    controller: App\Controller\Api\IsbnController::get
    methods:  [GET]
